### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by dslater82** [institut-de-genomique/HAPO-G#10]
I received various errors on not finding pthead, curl, and crypto references.  I think your CMakeLists.txt can be improved by adding 

target_link_libraries(hapog pthread)
target_link_libraries(hapog curl)
target_link_libraries(hapog crypto)

I did this and was able to get it to compile successfully.

**Comment by bistace** [comment]
Thank you for your suggestion, we will add it to the CMakeLists.

**Comment by bistace** [comment]
Sorry for the large delay, I pushed it this morning.
