### ISSUE TITLE
error using the -b option

### ISSUE THREAD

**Issue by chklopp** [institut-de-genomique/HAPO-G#12]
When I run the following command line 

`hapog.py --genome reference.fasta -b alignment.bam -o HapoG -t 16 -u`

I get the following error
```
Checking dependencies...
	Found BWA.
	Found Samtools.

Indexing the BAM file...

ERROR: Couldn't index bam file
Command '['samtools', 'index', 'bam/aln.sorted.bam']' returned non-zero exit status 127.
```

The HapoG directory is created, the HapoG/bam/aln.sorted.bam symbolic link exists. What should I change?

**Comment by bistace** [comment]
Hello,
there should be a `logs/samtools_index.e` and a `logs/samtools_index.o`, could you please paste their content?

**Comment by chklopp** [comment]
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by bistace** [comment]
I pushed something that could fix it, could you please download the latest github version and recompile to see if that fixes it?

**Comment by chklopp** [comment]
Thank you. samtools indexing is working now.
