### ISSUE TITLE
Do you recommend to polish hifi assemble results (like hifiasm or hicanu results) ?

### ISSUE THREAD

**Issue by xiekunwhy** [institut-de-genomique/HAPO-G#15]
Hi there,

Do you recommend to polish hifi assemble results (like hifiasm or hicanu results) ? And why ?

Best,
Kun

**Comment by bistace** [comment]
Hello,
we're currently doing some tests with the polishing of HiFi assemblies with HiFi reads. While I cannot give you a definitive answer, we believe that it could be particularly beneficial for heterozygous organisms, where the phasing should be of better quality after polishing.

**Comment by bishopia** [comment]
Hi,
If I had both hifi reads and illumina reads to polish a hifi assembly with, would you recommend a specific order to the polishing steps? Or can I use both the pe and single options at the same time? Thanks!
