### ISSUE TITLE
output, adding sequences from reads, and ratios? 

### ISSUE THREAD

**Issue by zpcohen** [institut-de-genomique/HAPO-G#16]
hello and thank you for this nifty program, it's become essential in resolving a concerning issue with our assemblies. I was wondering if you could provide some insight into how HAPO-G is making decisions about re-incorporating read data? Below you'll find some insertions that have been introduced, I was wondering how reliable they were given the ratios and what they mean. Thank you.

```sh
Scaff_3	493505	ref=A	read=ataA	readname=A00406:87:HFW2HDSXY:3:1360:1515:14231	hetero	ratio1=0.7419	ratio2=0.4237
Scaff_3	918557	ref=G	read=atttG	readname=A00406:87:HFW2HDSXY:3:2556:25852:32142	hetero	ratio1=0.8154	ratio2=0.5510
Scaff_3	928348	ref=A	read=attccA	readname=A00406:87:HFW2HDSXY:3:1674:28185:6277	hetero	ratio1=0.4722	ratio2=0.2250
```

**Comment by auryjm** [comment]
Hello and thank you for feedback on Hapo-G.

The second ratio is the proportion of reads in the pile (reads are added sequentially with a maximum coverage of 50) that have the given difference. And the first ratio involved only reads that were selected to be from the same haplotype. For example, for a heterozygous variation in a perfect world, one can expect to have ratio1=1 and ratio2=0.5.

In the Figure 2 of the Hapo-G publication, the second ratio does not take into account the two red-striped reads which come from a different haplotype (https://academic.oup.com/view-large/figure/246277757/lqab034fig2.jpg)

**Comment by zpcohen** [comment]
Thank you for the quick feedback and useful figure! So in these examples will they retain the ref=A or add the ataA, atta..etc from the reads? It looks like the read ratio is higher for reference?

**Comment by auryjm** [comment]
Yes, in this case it will change the reference sequence and use the read content (ataA, atttG, ...). The ratio in this case is lower, but perhaps the choice between the two haplotypes was made previously at another heterozygous site.

**Comment by zpcohen** [comment]
Gotcha, OK great thank you!
