### ISSUE TITLE
Polish before or after Redundans

### ISSUE THREAD

**Issue by Ben7124** [institut-de-genomique/HAPO-G#19]
Hello,
I was wondering if I should use Hapog on my assembly before using Redundans or after using Redundans (which does gap closing and returns a homozygous assembly)?
Thank you.

**Comment by bistace** [comment]
Hello,

I have not personally used Redundans but I would say that doing a round of polishing before and after Redundans would give the best results. If you do not want to polish before and after, using Hapo-G after would be better to 'clean up' the few errors that could have been introduced and phase the remaining SNPs.
