### ISSUE TITLE
It is possible to start from already produced BAM files?

### ISSUE THREAD

**Issue by andreaswallberg** [institut-de-genomique/HAPO-G#2]
Dear developers,

Thanks for an interesting tool. I wonder if it is possible to side-load BAM files in HAPO-G instead of aligning raw sequence data internally.

**Comment by bistace** [comment]
Hi,
it is indeed a good idea to be able to directly load a bam file. We will implement this change and will get back to you once it is done.

**Comment by bistace** [comment]
Just to clarify, you can already use a BAM file you produced by using the hapog binary in the build directory. However, by using this approach, you won't be able to multithread the polishing since it is done in the Python script.

**Comment by bistace** [comment]
Hi,
we added an option to directly give a sorted bam file to Hapo-G with the '-b' flag.

**Comment by andreaswallberg** [comment]
Many Thanks! Very interesting. I will take a look!
