### ISSUE TITLE
 ModuleNotFoundError

### ISSUE THREAD

**Issue by mergi-2674** [institut-de-genomique/HAPO-G#20]
I was trying to run hapo-g on a cluster on four nodes each with 128GB of RAM. I installed hapog through conda as it was written in the Readme.md. However, it always gives me an error which says 

"from Bio import SeqIO"

ModuleNotFoundError: No module named 'Bio' "

even if all the required libraries and modules are there.

What could be the possible reason for this and how should it be fixed?

Any input will be much appreciated!

**Comment by bistace** [comment]
Hello,

I just tested the conda build on several environments without any problem so to me it seems to be a problem with how you are launching your command. Could you please indicate the commands you are running (including the conda commands)?
