### ISSUE TITLE
Error with --threads 1

### ISSUE THREAD

**Issue by abretaud** [institut-de-genomique/HAPO-G#21]
Hi!
Found an error while writing a galaxy tool for Hapo-G:

```
ln: failed to create symbolic link 'chunks/chunks_1.fasta': No such file or directory
ln: failed to create symbolic link 'chunks_bam/chunks_1.bam': No such file or directory
```

This happens when running with the option `--threads 1`, any other value or omitting the option works well (default value seems to be 8)

I'll set to 2 by default in galaxy, but I guess it would be good to fix it at some point

**Comment by bistace** [comment]
Hello,

I just pushed a fix for it and will submit a PR to update the recipe on bioconda!
