### ISSUE TITLE
Minimum coverage for correction?

### ISSUE THREAD

**Issue by Andy-B-123** [institut-de-genomique/HAPO-G#22]
Hi, sorry I couldn't see this anywhere but just wanted to check does HapoG take into account depth when doing correction? I have a Nanopore assembly of ~400mb from 40x coverage and short-reads of around 20x coverage. I'm aware that the short-reads aren't as high depth as commonly used but unfortunately it was all that was available! 

I tried Pilon and it outputs when it has too low depth to call, just wanted to check if HapoG does a similar QC before correction? 

Thanks, have to say this is an awesome program, the run-time savings alone are so nice!

**Comment by bistace** [comment]
Hello and thank you for using Hapo-G!

The minimum coverage for correction is set to 3 so you need at least 3 reads over a site for this site to be corrected. 

With 20x you should be ok but there is a risk that some portions of the genome won't be greatly covered and the accuracy of the correction could be impacted.

**Comment by Andy-B-123** [comment]
Woo, wonderful, thanks for the info and very fast reply! Helpful and a good threshold. 

Cheers,

Andy
