### ISSUE TITLE
PackageNotFoundError

### ISSUE THREAD

**Issue by GuillaumeHolley** [institut-de-genomique/HAPO-G#23]
Hi,

I have installed Hapo-G through bioconda on our cluster using the instructions of the README and everything went just fine. However, as soon as I try Hap-G using `hapog` or `hapog --help`, I get the following error:

![hapog](https://user-images.githubusercontent.com/1068338/200343231-7ebde88d-f139-47b3-b98e-dbcd9725557e.PNG)

I would really appreciate if you could help :)

Thank you!
Guillaume

**Comment by bistace** [comment]
Hello,

indeed, I have the same error when trying to build it. I think something exterior to Hapo-G broke it. I will investigate the issue and come back to you.

**Comment by GuillaumeHolley** [comment]
Thanks!

**Comment by bistace** [comment]
I've updated the conda install to the 1.3.4 version and do not encounter the problem anymore. Could you please try to remove the conda env and reinstall Hapo-g? You can do it like this:
```bash
# Make sure to be in the base conda env
conda remove --all -n hapog
conda create -n hapog
conda install -c bioconda hapog
```

**Comment by GuillaumeHolley** [comment]
Hi @bistace,

Thanks for the fix, it works just fine now :)

Guillaume
