### ISSUE TITLE
How do I get a vcf file?

### ISSUE THREAD

**Issue by th2ch-g** [institut-de-genomique/HAPO-G#24]
Hi,

I need vcf file produced by HAPO-G.
Does HAPO-G have the ability to produce a VCF-like file that contains information about which bases have changed ?

**Comment by bistace** [comment]
Hello,

Hapo-g does not directly produce a VCF file but you have access to a `hapog_result/hapog.changes` file that looks like this:
```
bctg00000266_polished   13731   ref=G   read=A  readname=ERR6668103.34106548    hetero  ratio1=0.8750   ratio2=0.7778
bctg00000266_polished   13912   ref=G   read=-  readname=ERR6668103.9250320     homo    ratio1=0.9091   ratio2=0.9091
bctg00000266_polished   18728   ref=C   read=A  readname=ERR6668101.2620891     hetero  ratio1=0.1000   ratio2=0.2000
bctg00000266_polished   19397   ref=C   read=T  readname=ERR6668101.71739893    hetero  ratio1=0.2381   ratio2=0.3939
```

First column is contig name, second is the position on the contig, third is the original base(s) in the contig and fourth shows the corrected base(s).

**Comment by th2ch-g** [comment]
Thanks for answering my question.

I will take a look at ```hapog_result/hapog.changes```
