### ISSUE TITLE
hapog introduce non-codon character in the polished sequence

### ISSUE THREAD

**Issue by zmz1988** [institut-de-genomique/HAPO-G#26]
Hi, I used hapo-g for a while now, and recently just found that somehow for two of my assemblies, hapo-g add `=` in the genome sequence. 

I didn't notice it until I used the annotation lift-over tools to do the annotation transfer, and the annotation tool complains about the non-codon error. So I checked the `hapog.changes` file, and I got some of the lines as below:

```
Chr2_RagTag     4520897 ref=G   read=C  readname=m64045_210203_183949/19792785/ccs      hetero  ratio1=0.4444   ratio2=0.2660
Chr2_RagTag     4521143 ref=T   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2840
Chr2_RagTag     4521158 ref=C   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1111   ratio2=0.2840
Chr2_RagTag     4521179 ref=G   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2740
Chr2_RagTag     4521193 ref=T   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2720
Chr2_RagTag     4521219 ref=A   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1250   ratio2=0.3000
Chr2_RagTag     4521267 ref=C   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2800
Chr2_RagTag     4521292 ref=A   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2660
Chr2_RagTag     4521331 ref=A   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1250   ratio2=0.2520
Chr2_RagTag     4521347 ref=A   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2680
Chr2_RagTag     4521406 ref=T   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2700
Chr2_RagTag     4521415 ref=T   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2440
Chr2_RagTag     4521656 ref=A   read=G  readname=A00478:143:HY7CFDRXX:2:2252:6705:34648 hetero  ratio1=0.5000   ratio2=0.3580
Chr2_RagTag     4521672 ref=C   read=G  readname=A00478:143:HY7CFDRXX:2:2219:11894:20744        hetero  ratio1=0.7692   ratio2=0.2260
Chr2_RagTag     4521869 ref=A   read=C  readname=m64045_210203_183949/120783781/ccs     hetero  ratio1=0.0500   ratio2=0.2360
Chr2_RagTag     4522031 ref=G   read=T  readname=A00478:143:HY7CFDRXX:2:2175:6623:6230  hetero  ratio1=0.1250   ratio2=0.2600
```

May I ask what shall I do about it? Thanks!

**Comment by bistace** [comment]
Hello,

that is strange indeed and not something we have seen until now. Before investigating further, could you please:
  1. Verify that the reads file you use do not contain non-`ATCGN` nucleotides
  2. Verify that the assembly does not contain non-`ATCGN` nucleotides
  3. Check in the `hapog_chunks` directory if any fasta file contains non-`ATCGN` nucleotides

Could you also please indicate the command line you used to run HAPO-G?

**Comment by zmz1988** [comment]
Hi,

thanks for replying me so quick!

1. Reads are in fastq files. How could I check that? But these reads are quality filtered by softwares, and also used by multiple softwares to generate the assemblies, and I also used Pilon to polish my assemblies with the same input reads. I didn't find the non-ATGCN in my resulted assemblies, except the trial with hapo-G.

Also, I checked one read `Chr2_RagTag     4521143 ref=T   read==  readname=m64045_210203_183949/161679341/ccs     hetero  ratio1=0.1429   ratio2=0.2840
` that showed wrong in the .changes file
```
$ cat demultiplex.bc1003_BAK8A_OA--bc1003_BAK8A_OA.Q20.fastq | grep -A 1 'm64045_210203_183949/161679341/ccs' | head
@m64045_210203_183949/161679341/ccs
ATGTCATGTGTATGATTGAGTATAAGAACTTAAACCGTAACCCGATCTTAAAAGCCTAAGTAGTGTATCCTTGTTAACGA (omit the later parts)

$ cat demultiplex.bc1003_BAK8A_OA--bc1003_BAK8A_OA.Q20.fastq | grep -A 1 'm64045_210203_183949/161679341/ccs' | grep -o -P '.{0,3}=.{0,4}' | less
# returns nothing
```
2. yes, no non-ATGCN nucleotides in my pre-hapog-polish assembly. 

```
$ grep '=' ragtag.scaffold.fasta. # this is the original assembly fasta

$ grep -o -P '.{0,3}=.{0,4}' hapog.fasta    # after polishing by hapo-g
NAC=
CTT=ATGC
========
========
========
(omit hundreds of lines here)
```

3. no non-ATCGN found by grepping '='.
```
$ ls
chunks_1.bed        chunks_2.fasta      chunks_3.fasta.fai  chunks_5.bed        chunks_6.fasta
chunks_1.fasta      chunks_2.fasta.fai  chunks_4.bed        chunks_5.fasta      chunks_6.fasta.fai
chunks_1.fasta.fai  chunks_3.bed        chunks_4.fasta      chunks_5.fasta.fai
chunks_2.bed        chunks_3.fasta      chunks_4.fasta.fai  chunks_6.bed

$ grep -o -P '.{0,3}=.{0,4}' chunks_1.fasta
$ grep -o -P '.{0,3}=.{0,4}' chunks_2.fasta
$ grep -o -P '.{0,3}=.{0,4}' chunks_3.fasta
$ grep -o -P '.{0,3}=.{0,4}' chunks_4.fasta
$ grep -o -P '.{0,3}=.{0,4}' chunks_5.fasta
$ grep -o -P '.{0,3}=.{0,4}' chunks_6.fasta
# no '=' were found in chunks
```

here is the code I used. Sorry it's in a loop, as I have tens of files to run. Also just to clarify a bit that I merge the illumina reads with PacBio HiFi reads to do the polishing, because our HiFi coverage are pretty low (< 30x) and illumina coverage are not very high either (~50x).
```
for file in $(ls ./*.fasta)
do
name=$(basename $file | sed 's/.ragtag.scaffold.fasta//')
HiFi=$(find /Founder_PacBio_DNA/ -name "${name}*.fastq*")
Illumina_seq1=$(echo /Illumina_founder/${name}_R1.clean.fastq.gz)
Illumina_seq2=$(echo /Illumina_founder/${name}_R2.clean.fastq.gz)
echo "${name} start hapog"
minimap2 -t 20 --secondary=no -ax map-hifi $file ${HiFi} > ${name}.hifi.sam
samtools view -Sb ${name}.hifi.sam | samtools sort -@ 20 > ${name}.hifi.bam
#bwa index $file
bwa mem -t 20 -o ${name}.illumina.sam ${file} ${Illumina_seq1} ${Illumina_seq2}
samtools view -Sb ${name}.illumina.sam | samtools sort -@ 20 > ${name}.illumina.bam
samtools merge -@ 20 ${name}.merged.bam ${name}.hifi.bam ${name}.illumina.bam
samtools sort -@ 20 ${name}.merged.bam > ${name}.merged.sorted.bam
samtools index ${name}.merged.sorted.bam
#hapog.py --genome ${file} -b ${name}.merged.sorted.bam -o ${name}_hapog -t 30 -u
echo "${name} done hapog"
done
```

**Comment by bistace** [comment]
Using a combination of short reads and long reads (with a mixture of bwa and minimap2) has not been tested so I cannot guarantee that it works. 
Could you please do first a polishing with the short reads and then a polishing with the long reads to confirm that it is not causing this issue?

Which version of HAPO-G are you using? If you installed it via the Github repository, you can see the version in the `setup.cfg` file. Otherwise just updating it with conda should do the trick to see if there is not a newer version.

**Comment by zmz1988** [comment]
I used the conda version, and didn't find how to check the version of hapo-g

**Comment by bistace** [comment]
You can use `conda list | grep hapog`

**Comment by zmz1988** [comment]
Hi, I used 
```
$ conda list | grep hapog
hapog                     1.3             py310h14c3975_0    lbgb_cea
```

I did now by using illumina reads and then hifi polishing. But when I check the final hapog.changes after hifi polishing, quite a lot of the changes are small insertions/deletions with status of `homo`, like below

```
Chr2_RagTag     505662  ref=C   read=-  readname=m64045e_210625_171429/18221130/ccs     homo    ratio1=1.0000   ratio2=1.0000
```

Does `homo` mean homogenous loci? Considering that hifi reads have the reputation of small deletion/insertion sequencing errors, I would like to skip all of such loci that shows homogeneously different (single or double nucleotides insertion or deletion) from illumination reads. Is it possible to do this?

Thanks!

**Comment by bistace** [comment]
Hello,

this is not the last version of Hapo-G (1.3.4). Could you please check that you still have this issue with the latest version? You can obtain it by running the following commands:
```bash
conda remove --all -n hapog
conda create -n hapog
conda activate hapog
conda install -c bioconda hapog
```

As for your question, it is not yet possible to skip some corrections as it is the base that the majority of reads agree on. I was not aware that the PacBio HiFi reads had a significant indel problem, is it specific on the genomes you are working on?

**Comment by zmz1988** [comment]
Hi, I just checked for the polishing results, and it seems that with the new version, the problem still exist, when using the combined .bam file. Just to let you know. :)

**Comment by bistace** [comment]
Hello,

would it possible for you to share the BAM file and the assembly Fasta file to see if we can reproduce the issue? 

If it is possible, please shoot an email to bistace@genoscope.cns.fr so I can give you a link to securely upload your data.

**Comment by jaxlub** [comment]
Hello, 
I was wondering if this issue was resolved? 
I am working with Hapo-g with both long read and short read sequences. I first ran Hapo-g with the short-reads (no non ATCG's present in pre-genome) which outputs a polished genome with lowercase letters introduced into output sequences (```ATTTAtTTTTC```). I then run Hapo-g with a minimapped bam file with long-reads. At this point the output genome sequence looks like this: 
```
>contig_100000_polished
ATCTCTCCCGCTTAATAATCTCCCATCATCACCACGACGCTATCGAGaAAAAAAAAAAGT
AGAATATAAAATTAtTTTTTTTTTTATAAAATTTCTTTAATATTACTTTTACAAATGTTT
AAATATCAAAATACAGtTTTTTTTTTCCTTCTTCAAATGCTATTCATTTGGTATCTCCCA
AGGGTATGTAAGGGTTTTTCCTTTTATCtTTTTTTTTTTCTTCCTTTCTCTCACCATTTC
ACATTTCGcattacatccgaAGtACCGATtcggaCTTTTATTCTTCCGGACTCGGGTGGC
AGaaAAAAAAAAAAAATCAAGAAAATCAAATCAAAGATTTACTGTAAAGGAGACTGGGGA
AATACATGTGCACGCTAAAAATCTGTGTTTATCTTTAACAAGAAAGGtTTTTTTTTTTTT
GTGATTTTTCTTTTATGCAAAGGAGaAAAAAAAAGCTGTTTCGTGTTTCAACAGCTAGAA
AACATACGGATGGaAAAAAAAAAATAGTGAAACACTAAATCACGAGCTACAAAAACCGAT
TATATGACTTTGTGGGGCTTCAAGAGAAAAAATTAAGAACGAtTTTTTTTTTTCTCTCTT
ATGATGaAAAAAAAAAAAGTTTCGTTTCCCAGAATATGGCTCGAATATATTTAAAAATAA
TAAAGGCAACTTCGAtTTTTTTTTTTTTAAACTGAGAGTTGCTTAAGATAATAACACTTA
GGTGGTGTTCtTTTTTTTTTTTAAGCAGACATCCATAGAATTTTTAATTCCTTTTTTACA
```
I then use ntlink to scaffold the genome (which has some but not a lot of lowercase letters still from first round of hapo-g) before repolishing in the same way as before - short reads first (genome output has some lowercase letters) and then polish with long-read minimapped bam file. After this second round of long-read bam polishing the reads look like this:
```
=T==========================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
============================================================
========================================TTCGAACCAGCGTTC=AGGA
=AATGATGTGT=TTTGGAGATAGT=A=GCATGAA=CGAAGATT=CT=T=TTTAGTA=GAA
TTGCTGTGTCGTCCGCAAACATAGC==GTGTAGTGTTTGGAGTATTTGGAATGTCA=TAA
=AAA=A=GTTAAAAAGTATAGGTCCTAATTTAGAGCCTTG=GGGACTCCAGCATTAATAG
GGTGTATAGTAGAAGT=TCTTGTGAGTGGCGGNCTTGAAAAG=TCTGCCGAGAAGGT=TG
=GTGTATTAAATGTA=AATATCAGCTGGCATTTTATGCTGAATTAACTTGTAAATAAGAG
CT=GATGCCAGACTCG=TCAAAAGCCTTCTCG=TATCAAA=AAGATGGCGCCAGTATGCA
TGCG=TTTTGGAATCCATCGAAGAT=A=TTCTGAAACACGTAGCAACTGGTGTGTAGTGG
{and so forth}
```
Steps I used on short reads
```
hapog --genome genome.fasta --pe1 clean_short_reads_1.trim.fastq.gz --pe2 clean_short_reads_2.trim.fastq.gz -o polishing -t 16 -u
```

Steps I used to convert long-reads into bam file
```
 minimap2 -ax map-ont genome_fixed_headers.fasta long_reads.fastq.gz > aligned_long_reads.sam
 samtools sort -o sorted_long_reads.sam aligned_long_reads.sam
 samtools view -bS sorted_long_reads.sam -o long_reads_sorted.bam
 hapog --genome genome_fixed_headers.fasta -b long_reads_sorted.bam -o polishing -t 16 -u
```
I am using Hapo-g 1.3.7

Any input as to where I might be going wrong would be greatly appreciated!
Thanks!
Jax

**Comment by bistace** [comment]
Hello,
thank you for including the steps that lead to the issue. We will try to reproduce it and come back to you.

**Comment by bistace** [comment]
Hello,
it seems like the issue occurs when the BAM file contains secondary alignments, as these don't include the sequence directly in the record. Could you please relaunch your minimap2 alignments with the `secondary=no` option?

We have added this in the Readme so others can benefit from this.

**Comment by jaxlub** [comment]
Yes that worked! Thank you very much!
