### ISSUE TITLE
Question: how HAPO-G handles N in reads?

### ISSUE THREAD

**Issue by Yutang-ETH** [institut-de-genomique/HAPO-G#27]
Hi HAPO-G team,

Thank you very much for developing this tool. I am just wondering how HAPO-G handles Ns in the reads? I know nextpolish would introduce Ns into the assembly after polishing if there are any Ns in the reads, https://nextpolish.readthedocs.io/en/latest/FAQ.html#why-does-the-contig-n50-of-polished-genome-become-shorter-or-why-does-the-polished-genome-contains-some-extra-n. What will happen if there are Ns in reads after HAPO-G polishing? 

Thank you very much and look forward to your explanation.

Best wishes,
Yutang

**Comment by auryjm** [comment]
Hi Yutang,
Thank you for your message and your interest in Hapo-G.
Theoretically no. Indeed the reads are aligned to the draft genome and Hapo-G deals with pile of alignments (nucleotide). In almost all cases, the N's should be in the minority. It may depend on the exact context, but we can be confident that the polished sequence does not contain extra N's.
Jean-Marc

**Comment by Yutang-ETH** [comment]
Hi Jean-Marc,

Thank you very much for your reply. 

If I understood you correctly, then what you meant is if the proportion of N is tiny (normally should be), N will not be introduced to the assembly. However, does it also mean if there are many Ns at a position, the N could be introduced to the assembly? Do you specifically filter Ns or how do you deal with Ns? I am asking because some of my reads have a certain portion of Ns, fastQC tells me the reads are good, but when I ran nextpolish, I found Ns in my contigs, which is not good. So, I am worried that the same thing could happen to HAPO-G.

Thank you very much and look forward to your reply.

Best wishes,
Yutang

**Comment by auryjm** [comment]
Yes, if the proportion of N's is more than 80%, an N will replace the initial nucleotide. 
But if you have a lot of cases like this, we can try to avoid this behavior. 
Jean-Marc

**Comment by Yutang-ETH** [comment]
Thank you very much for your clarification. Just to be safe, I will remove any Ns from my reads prior polishing.

Best wishes,
Yutang
