### ISSUE TITLE
Question: how about polishing a phased diploid genome assembly?

### ISSUE THREAD

**Issue by Yutang-ETH** [institut-de-genomique/HAPO-G#28]
Hi HAPO-G team,

Last night I started HAPO-G to polish a phased diploid genome assembly made from ONT reads with a size around 4.4 Gb using 60x Illumina short reads, just after 16 hours, it finished successfully. I have to say I really like HAPO-G, and it really amazed me by its nicely organized output folder structure and its fast speed. 

However, I want to confirm something with you:

- First, is it a good practice to polish a diploid assembly with short reads from whole genome sequencing? I polished the diploid assembly instead of each haplotype separately because I thought when map reads to a phased diploid assembly, reads will be mapped accordingly to the right haplotype where they are from so that less phase switches will occur after polishing. What do you think? 

- I checked the hapog.changes file from my last run with the phased diploid assembly, I found most (93% = lines with homo/all lines) of the changes were classified as homo. I guess this suggests that my assembly is really phased (at least most alleles were separated), and reads did map to the corresponding haplotype correctly. What do you think? By the way, for the homo variation, ratio1 and ratio2 are mostly 1. I guess the ratio means the allele frequency you described in your paper, but why there are two ratios?

Thank you very much again for making this brilliant tool and look forward to your reply.

Best wishes,
Yutang

**Comment by auryjm** [comment]
Hi Yutang,

Thank your for your kind message, it's always encouraging to see that our tools are useful !

- I would say yes, as polishing the diploid assembly will ensure better alignment of individual reads. However, in case you have an haploid assembly, Hapo-G will try to avoid phase switches (within the limit of read length and SNP frequency).
- Indeed, if most of the changes are homo it may indicate that your assembly is correctly phased. There are two ratios, one for the pile of alignment used for polishing (i.e. without reads that may correspond to the second haplotype) and one for the whole set of alignments.

Hope this helps,

Jean-Marc

**Comment by Yutang-ETH** [comment]
Hi Jean-Marc,

Thank you very much for your comments, they are very helpful, and I have to say this again, HAPO-G is really wonderful.

Cheers,
Yutang
