### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Yutang-ETH** [institut-de-genomique/HAPO-G#29]
Hi HAPO-G team,

I hope you are well and thank you very much again for your nice work.

Recently, while I was using hapog a lot to polish my assemblies, I met a problem which is same to the issue described in #5. At the error correction step, bam files were processed in parallel with the same number of jobs as the number of threads set for read alignment. My machine has 60 CPUs and 900 Gb memory, however, with 60 CPUs, haplog used more than 900 Gb memory, which caused it to stop.

Maybe a way to avoid large memory usage is to not submit all the correction jobs in one go, for example, for my machine, maybe first process the first 30 jobs and then finish the next 30 ones. So, is it possible to have another option for haplog to control the number of bam files processed in parallel to avoid large memory usage?

I am using Illumina pair-end short reads correcting ONT-based assemblies with the latest hapog.

Look forward to your reply and thank you very much.

Oh, by the way, I found in the bwa mem command, the memory usage for samtools sort is set to 5 Gb, which might not be good for machines with not a very high memory.

Best wishes,
Yutang

**Comment by bistace** [comment]
Hello and thank you for using Hapo-G!

When you say that it used 900Gb of memory, do you know which step made it use that much? We've used Hapo-G extensively to polish very large genomes and we never encountered such a high memory usage.

We set the samtools sort file size to 5Gb as it was problematic when using the default size for large genomes (it was creating a lot of files). However I agree with you and will move that to an option for smaller machines!

**Comment by Yutang-ETH** [comment]
Hi,

Thank you very much for your reply. It was the correction step which caused the very high memory usage. Or more specifically, correcting with split bam files in 48 or 60  jobs parallel caused the problem. There was always one job failed. 

I guess the high memory usage is not only caused by the large genome size, but also related to read coverage. My genome size is around 2.2 ~ 3.0 Gb, and if the read coverage is below 40-fold, I never had the issue. However, for some genotypes, we have coverages above 60-fold, which gave me the problem.

I really appreciate your work and I don't mean to push you to the direction I want. I just want to give you the feedback as a user. Anyway, thank you very much again for your help and your brilliant work.

Best wishes,
Yutang

**Comment by bistace** [comment]
Hello,

Hapo-G 1.3.6 has been released on Bioconda with two new arguments:
  - `--samtools-mem`: this is the same thing as `samtools sort -M` option
  - `--hapog-threads`: this controls the number of Hapo-G processes that run in parallel

Could you please update to this version and tell me if that solves your problem? 

Just out of curiosity, did you try to run one of the commands that failed just by itself to see how much memory it was using?

**Comment by Yutang-ETH** [comment]
Wow! Thank you very much for your update! I will check the new version and give you the feedback.

I did manually run the failed command, but I didn't check the memory used by that command specifically. The exceeding memory usage was observed while all the jobs were running in parallel. 

Best wishes,
Yutang

**Comment by Yutang-ETH** [comment]
Hi Benjamin,

I hope you are well. 

First of all, I would like to thank you for your quick implementation of the two options I discussed with you.

Now, after trying the Hapo-G 1.3.6, I can confirm that it works perfectly with the  --hapog-threads! Great job, and thank you very much again.

Best wishes,
Yutang
