### ISSUE TITLE
Explanation of hapog.changes

### ISSUE THREAD

**Issue by bsb2014** [institut-de-genomique/HAPO-G#30]
Could you please explain the changes in the hapog.changes. The Hapo-G version is 1.3.3.

case1
contig_1        2112    ref=T   read=C  readname=xxx   homo    ratio1=1.0000   ratio2=1.0000
Does case1 mean  C is homo among reads and different from ref?

case2
contig_1        93010   ref=T   read=-  readname=xxx    hetero  ratio1=0.2692   ratio2=0.2692
Does case2 mean  -  is hetero  among reads, say **_-/T_** ?

case3
contig_1        119614  ref=G   read=gG readname=xxx   homo    ratio1=1.0000   ratio2=1.0000
What does **_low-case g_** mean in the case3?

Thanks

**Comment by aldendirks** [comment]
I would also benefit from and appreciate more documentation of how to understand and interpret hapog.changes and hapog.fasta. Thanks!
