### ISSUE TITLE
Plant genome

### ISSUE THREAD

**Issue by SanSanMX** [institut-de-genomique/HAPO-G#37]
Hello dear Hapo-G developers,

I am working for the first time with a genome (diploid plant genome) and I have a couple of doubts about the best use of Hapo-G. I generated an assembly with Canu and then used HaploMerger2 to separate the haploid subsets, the reference and the alternative and I would like to know which would be the best alternative to polish my assemblies with Illumina 30X reads.

I will greatly appreciate your comments.

**Comment by auryjm** [comment]
Hello,
Generally, we recommend polishing the haploid (ref) version using the whole Illumina datasets. If you polish both assemblies (ref + alt) at the same time, it may result in uncovered and unpolished regions. In a two-step mode, you will use reads from both haplotypes each time.
Jean-Marc

**Comment by SanSanMX** [comment]
Thank you very much for your response, I will execute it like this. I have one more question, is there an estimate of RAM memory per genome size to analyze? My reference genome is about 3Gb.

**Comment by auryjm** [comment]
It's difficult to say, but it should be okay with less than 32GB. For a 3GB genome, try to use as many cores as possible; we generally use 36 cores.

**Comment by SanSanMX** [comment]
Thank you very much again, one last question, regarding time, do you have any estimates on a similar genome? Let's say with 36 cores.

Thank you.

**Comment by auryjm** [comment]
It depends on how fragmented your assembly is. Many small contigs are easier to distribute over the 36 cores, but if you have only two giant chromosomes, only 2 cores will be used, and it will be slower. However, in general, Hapo-G is fast and should not run for more than two days in our case, maybe overnight depending on your assembly stats.

**Comment by SanSanMX** [comment]
Thank you very much for answering my questions, I will be using this tool. You can close this issue as resolved.

**Comment by auryjm** [comment]
Thank you, and keep us in touch if you encounter any problems!
