### ISSUE TITLE
Phased assembly polishing

### ISSUE THREAD

**Issue by Karenmagh** [institut-de-genomique/HAPO-G#39]
Hello dear developers,

I just generated a phased assembly of a plant genome with the PECAT tool and got a primary/alternate pair.
I want to polish both genomes with Illumina reads 20X and I would like to know if you recommend
polishing each genome separately or concatenating both and polishing them together.

I would greatly appreciate your response.

**Comment by auryjm** [comment]
Hello,
Sorry for our late reply. You can do both, but having both haplotypes simultaneously might be better to limit cross-mapping between them. However, given your low coverage, polishing the haplotypes separately may be a better option.
Unfortunately, the hash that keeps the FASTQ sequence names corresponding to the other haplotype is purged when the end of the reference sequence is reached.

Hope this helps!
