### ISSUE TITLE
ERROR: Hapo-G didn't finish successfully, exit code: -9

### ISSUE THREAD

**Issue by Mondlii** [institut-de-genomique/HAPO-G#5]
Hi, I am relatively new to bioinformatics and I was hoping to use your tool to improve my assembly draft. I have a 690MB draft assembly and raw reads of 260x coverage. The tool was running for more than 3 days and then it stopped citing.

Command: hapog.py --genome Draft.fa --single /AC_SP6/PromethION.fq --threads 8
ERROR: Hapo-G didn't finish successfully, exit code: -9
Faulty command: miniconda3/envs/SLR/bin/build/hapog -b chunks_bam/chunks_2.bam -f chunks/chunks_2.fasta -o hapog_chunks/chunks_2.fasta -c hapog_chunks/chunks_2.changes 

I am led to believe that this is related to an out of memory error the server gave out for the run. I was running on 450gb mem and 16 cores. the command is below. I would like to know if there was a way to work around memory limits? If this issue is due to the size of the data fed to the tool would using a subset of the sequencing data fix the issue? And also would it be possible to resume the run instead of starting over?

Thank you for your help

**Comment by auryjm** [comment]
Hi,
What kind of data you used to polish your assembly draft is not clear to me. From the name of the input file, I'm assuming you used nanopore reads as input. If this is true, keep in mind that unfortunately Hapo-G can only use high-quality reads (Illumina or PACBIO HiFi), and the error is most likely from the input data.
Thank you,
