### ISSUE TITLE
Error in bwa mem and samtools sort, return code: 256

### ISSUE THREAD

**Issue by myco-bradshaw** [institut-de-genomique/HAPO-G#6]
Hello,

I am having some Issues running HAPO-G, I have tried using both the conda installation as well as compiling it separately, and under both situations, I get the same error when running the pipeline.

Launching mapping on genome...
Error in bwa mem and samtools sort, return code: 256
Faulty command: bash -c 'bwa mem -t 36 assembly.fasta /path/to/read_R1 /path/to/read_R2 2> logs/bwa_mem.e | samtools sort -m 5G -@ 36 -o bam/aln.sorted.bam - 2> logs/samtools_sort.e

when I look at the the log files its looks like and issue arrose in bwa_mem.e :

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 2434218 sequences (360000259 bp)...
[M::process] read 2432188 sequences (360000049 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (20, 600263, 17, 19)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (133, 253, 595)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1519)
[M::mem_pestat] mean and std.dev: (315.11, 307.58)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1981)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (185, 234, 290)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 500)
[M::mem_pestat] mean and std.dev: (239.67, 78.97)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 605)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (61, 100, 6386)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 19036)
[M::mem_pestat] mean and std.dev: (1621.82, 2653.72)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 25361)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (159, 181, 443)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1011)
[M::mem_pestat] mean and std.dev: (324.58, 259.23)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1362)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 2434218 reads in 446.364 CPU sec, 13.348 real sec
[fputs] Broken pipe

I am unsure exactly how to proceed do you have any suggestions?

**Comment by bistace** [comment]
Hello,

it seems that the samtools step crashed, could you please show me what is inside `logs/samtools_sort.e`?

**Comment by myco-bradshaw** [comment]
Yes, the error from logs/samtools_sort.e:

samtools sort: couldn't allocate memory for bam_mem

**Comment by bistace** [comment]
It means that the samtools sort ran out of RAM. As we allocate 5G of RAM per samtools sort thread, you should relaunch hapo-g with a lower number of threads.
