### ISSUE TITLE
conda running code

### ISSUE THREAD

**Issue by desmodus1984** [institut-de-genomique/HAPO-G#7]
Hi,

I installed HAPO-G in conda
which code should I use for running?

With this code:
module load python
source activate assembly-Y
python3 HAPOG_ROOT/hapog.py  --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta \   # Fasta file of the genome to polish
  -b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam -o myse -t 48

I got the following log:
python3: can't open file 'HAPOG_ROOT/hapog.py': [Errno 2] No such file or directory
/var/spool/slurmd/job5228454/slurm_script: line 12: -b: command not found

Thanks;

**Comment by bistace** [comment]
Hello,

on conda, you can just invoke `hapog.py` as it will be in your PATH.

**Comment by desmodus1984** [comment]
> Hello,
> 
> on conda, you can just invoke `hapog.py` as it will be in your PATH.

Hi I ran the following command:
hapog --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta # Fasta file of the genome to polish
-b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam -o myse -t 48

 and I got the following message:
usage: hapog [-h] --genome INPUT_GENOME [--pe1 PE1] [--pe2 PE2]
             [--single LONG_READS] [-b BAM_FILE] [-u] [--output OUTPUT_DIR]
             [--threads THREADS] [--bin HAPOG_BIN]
hapog: error: unrecognized arguments:
/var/spool/slurmd/job5287196/slurm_script: line 12: -b: command not found

What am I doing wrong?

**Comment by bistace** [comment]
Hi,

if you copied and pasted the entire command line you ran in your previous comment, you have forgotten to include line breaks.  Basically, bash will understand that you tried to run the following two commands:


First one:
```
hapog --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta # Fasta file of the genome to polish
```
Second one:
```
-b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam -o myse -t 48
```

As you can see, these are probably not the ones you intended to run.


Instead, I recommend that you run (assuming the input files are correct):
```
hapog --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta  -b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam -o myse -t 48
```

You can also use this multi-lines version (notice the new line breaks):
```
hapog --genome  /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta \
    -b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam \
    -o myse \
    -t 48
```

**Comment by desmodus1984** [comment]
> Hi,
> 
> if you copied and pasted the entire command line you ran in your previous comment, you have forgotten to include line breaks. Basically, bash will understand that you tried to run the following two commands:
> 
> First one:
> 
> ```
> hapog --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta # Fasta file of the genome to polish
> ```
> 
> Second one:
> 
> ```
> -b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam -o myse -t 48
> ```
> 
> As you can see, these are probably not the ones you intended to run.
> 
> Instead, I recommend that you run (assuming the input files are correct):
> 
> ```
> hapog --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta  -b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam -o myse -t 48
> ```
> 
> You can also use this multi-lines version (notice the new line breaks):
> 
> ```
> hapog --genome  /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta \
>     -b ../MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam \
>     -o myse \
>     -t 48
> ```

Hi,

I just did that; I used the following code:

```
hapog --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta \
        -b /fs/scratch/PHS0338/appz/MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam \
        -o myse \
        -t 48
```
I even checked if hapo-g was installed in conda and it is, and I got the following error:
/var/spool/slurmd/job5303212/slurm_script: line 11: hapog: command not found

I am very confused because, when it was close to work the error was:
usage: hapog [-h] --genome INPUT_GENOME [--pe1 PE1] [--pe2 PE2]
             [--single LONG_READS] [-b BAM_FILE] [-u] [--output OUTPUT_DIR]
             [--threads THREADS] [--bin HAPOG_BIN]
hapog: error: unrecognized arguments:
/var/spool/slurmd/job5287196/slurm_script: line 12: -b: command not found

and now I am using hapog and it is not running.

**Comment by bistace** [comment]
Hello,

this is weird. I just checked on my system with a fresh installation and everything seems to work.

Here is what I think you should do:
1. Create a fresh conda env for hapog (make sure you are in the base env while running this):
```
conda env remove --name hapog (replace hapog by the name of your conda env)
conda create -n hapog
conda activate hapog
conda install -c lbgb_cea hapog
```

2. Execute hapog by invoking `hapog.py`which is the wrapper script (make sure that you are in the hapog conda env that you just created and installed hapog into):
```
hapog.py --genome /users/PHS0338/jpac1984/data/SuperExt.scaff.fasta \
        -b /fs/scratch/PHS0338/appz/MaSuRCA-4.0.5/TGI_myse/SuperExt.scaff.fasta.alignSorted.bam \
        -o myse \
        -t 48
```
