### ISSUE TITLE
ERROR: Hapo-G didn't finish successfully, exit code: -8

### ISSUE THREAD

**Issue by JonEilers** [institut-de-genomique/HAPO-G#8]
Hi, 
Ran Hapo-g successfully twice, on the third round I get this error. 

```bash
hapog.py \
	--genome /home/jon/Working_Files/hapo-g/round_2/hapog_results/hapog.fasta \
	--single /home/jon/Working_Files/sea_cuke_species_data/apostichopus_japonicus/apostichopus_japonicus_raw_genome_seq_data/pacbio_SRR6282347.1.fastq \
	--output /home/jon/Working_Files/hapo-g/round_3 \
	--threads 70 \
	-u

Checking dependencies...
	Found BWA.
	Found Samtools.

Non alphanumeric characters detected in fasta headers. Renaming sequences.

Launching mapping on genome...
Done in 2809 seconds

Indexing the BAM file...
Done in 286 seconds

Fragmenting the genome into 70 chunks of 11,489,433 bases (depending of scaffold sizes)
Done in 11 seconds

Extracting bam for each chunk
Done in 60 seconds

Launching Hapo-G on each chunk
ERROR: Hapo-G didn't finish successfully, exit code: -8
Faulty command: /home/jon/miniconda3/envs/hapog/bin/build/hapog -b chunks_bam/chunks_69.bam -f chunks/chunks_69.fasta -o hapog_chunks/chunks_69.fasta -c hapog_chunks/chunks_69.changes
```

**Comment by bistace** [comment]
Hello,

could you please paste the content of the `/home/jon/Working_Files/hapo-g/round_3/logs/hapog_chunks_69.o` and `/home/jon/Working_Files/hapo-g/round_3/logs/hapog_chunks_69.e` files?

**Comment by JonEilers** [comment]
both of those specific files are empty. It looks like only the hapog_chunks_#.o files have content. The hapog_chunks_#.e files are all empty

**Comment by bistace** [comment]
That's strange, could you try launching the faulty command? This should work:
```
cd /home/jon/Working_Files/hapo-g/round_3
/home/jon/miniconda3/envs/hapog/bin/build/hapog -b chunks_bam/chunks_69.bam -f chunks/chunks_69.fasta -o hapog_chunks/chunks_69.fasta -c hapog_chunks/chunks_69.changes
```

Also, is the fasta file `chunks/chunks_69.fasta` containing something or is it empty?

**Comment by JonEilers** [comment]
The fasta file `chunks/chunks_69.fasta` does have content. the `chunks_bam/chunks_69.bam also has some content. [here](https://github.com/JonEilers/error_logs/blob/main/chunks_69.bam) is a link to the bam file and [here](https://github.com/JonEilers/error_logs/blob/main/chunks_69.fasta) is a link to the fasta file. Below is the terminal output from running the requested command. 

```bash
(hapog) jon@jon-PowerEdge-R910:~/Working_Files/hapo-g/round_3$ /home/jon/miniconda3/envs/hapog/bin/build/hapog -b chunks_bam/chunks_69.bam -f chunks/chunks_69.fasta -o hapog_chunks/chunks_69.fasta -c hapog_chunks/chunks_69.changes
Floating point exception (core dumped)
```

**Comment by bistace** [comment]
Thanks a lot for providing the bam, we will look into this and will keep you informed.

**Comment by JonEilers** [comment]
Awesome, thanks! In case you want to try reproducing this - the genome can be found [here](https://www.ncbi.nlm.nih.gov/genome/?term=apostichopus%20japonicus) and the pacbio is [here](https://www.ncbi.nlm.nih.gov/sra/SRR6282347)

**Comment by bistace** [comment]
After inspecting the BAM file, it seems that it doesn't contain any alignment. It is not normal and something might have gone wrong during the alignment step, like a full disk. Could you please check that everything went as expected?

On our side, we're going to add checks for this situation.

**Comment by bistace** [comment]
We just pushed a version that improves the handling of empty BAM files on conda and on github. Could you please check if that solves your issue?

**Comment by JonEilers** [comment]
Well I am feeling a little silly. I totally forgot that I had renamed the fastq file so it'd work with [dentist](https://github.com/a-ludi/dentist). So ya, no surprise the bam file is empty as there was no fastq file with that name. I'm running it with hapo-g version 1.1 at the moment. I'll run it with hapo-g version 1.2 after and will close this issue if all is working. Thanks for the assistance and sorry for wasting your time! One suggestion would be to add a check if file exists and error message if a file doesn't exist. Cheers!

**Comment by JonEilers** [comment]
got the same error with version 1.1. reran with version 1.2 and that seemed to do the trick. Thanks!
